# Default values for sock-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
    registry: ''

java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

cartsdb:
    image:
        repo: mongo
        tag: 4.4.0
    resources:
        requests:
            cpu: 500m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi
    persistentVolume:
        storageClass: ''
        size: 512Mi

cataloguedb:
    image:
        repo: weaveworksdemos/catalogue-db
        tag: 0.3.0
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi

ordersdb:
    image:
        repo: mongo
        tag: 4.4.0
    resources:
        requests:
            cpu: 500m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi
    persistentVolume:
        storageClass: ''
        size: 512Mi

sessiondb:
    image:
        repo: redis
        tag: alpine
    resources:
        requests:
            memory: 256Mi
            cpu: 250m
        limits:
            memory: 256Mi
            cpu: 250m
    persistentVolume:
        storageClass: ''
        size: 512Mi

userdb:
    image:
        repo: weaveworksdemos/user-db
        tag: 0.4.0
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi

zipkinmysql:
    image:
        repo: openzipkin/zipkin-mysql
        tag: 1.20.0
    resources:
        requests:
            memory: 256Mi
            cpu: 250m
        limits:
            memory: 768Mi
            cpu: 1
