all:
  hosts:
    otus-kubmaster-infra-01:
      access_ip: 10.128.0.29
      ansible_host: 10.128.0.29
      ip: 10.128.0.29
    otus-kubmaster-infra-02:
      access_ip: 10.129.0.10
      ansible_host: 10.129.0.10
      ip: 10.129.0.10
    otus-kubmaster-infra-03:
      access_ip: 10.130.0.32
      ansible_host: 10.130.0.32
      ip: 10.130.0.32
    otus-kubworker-infra-01:
      access_ip: 10.128.0.20
      ansible_host: 10.128.0.20
      ip: 10.128.0.20
    otus-kubworker-infra-02:
      access_ip: 10.129.0.20
      ansible_host: 10.129.0.20
      ip: 10.129.0.20
    otus-kubworker-app-01:
      access_ip: 10.130.0.18
      ansible_host: 10.130.0.18
      ip: 10.130.0.18
  children:
    kube-master:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    kube-node:
      hosts:
        otus-kubworker-infra-01:
        otus-kubworker-infra-02:
        otus-kubworker-app-01:
    etcd:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
