all:
  hosts:
    otus-kubmaster-infra-01:
      access_ip: 10.128.0.4
      ansible_host: 10.128.0.4
      ip: 10.128.0.4
    otus-kubmaster-infra-02:
      access_ip: 10.129.0.29
      ansible_host: 10.129.0.29
      ip: 10.129.0.29
    otus-kubmaster-infra-03:
      access_ip: 10.130.0.23
      ansible_host: 10.130.0.23
      ip: 10.130.0.23
    otus-kubworker-infra-01:
      access_ip: 10.128.0.5
      ansible_host: 10.128.0.5
      ip: 10.128.0.5
    otus-kubworker-infra-02:
      access_ip: 10.129.0.21
      ansible_host: 10.129.0.21
      ip: 10.129.0.21
    otus-kubworker-app-01:
      access_ip: 10.130.0.7
      ansible_host: 10.130.0.7
      ip: 10.130.0.7
  children:
    kube-master:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    kube-node:
      hosts:
        otus-kubworker-infra-01:
        otus-kubworker-infra-02:
        otus-kubworker-app-01:
    etcd:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
