all:
  hosts:
    otus-kubmaster-infra-01:
      access_ip: 10.128.0.8
      ansible_host: 10.128.0.8
      ip: 10.128.0.8
    otus-kubmaster-infra-02:
      access_ip: 10.129.0.33
      ansible_host: 10.129.0.33
      ip: 10.129.0.33
    otus-kubmaster-infra-03:
      access_ip: 10.130.0.25
      ansible_host: 10.130.0.25
      ip: 10.130.0.25
    otus-kubworker-infra-01:
      access_ip: 10.128.0.30
      ansible_host: 10.128.0.30
      ip: 10.128.0.30
    otus-kubworker-infra-02:
      access_ip: 10.129.0.13
      ansible_host: 10.129.0.13
      ip: 10.129.0.13
    otus-kubworker-app-01:
      access_ip: 10.130.0.32
      ansible_host: 10.130.0.32
      ip: 10.130.0.32
  children:
    kube-master:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    kube-node:
      hosts:
        otus-kubworker-infra-01:
        otus-kubworker-infra-02:
        otus-kubworker-app-01:
    etcd:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
