all:
  hosts:
    otus-kubmaster-infra-01:
      access_ip: 10.128.0.25
      ansible_host: 10.128.0.25
      ip: 10.128.0.25
    otus-kubmaster-infra-02:
      access_ip: 10.129.0.34
      ansible_host: 10.129.0.34
      ip: 10.129.0.34
    otus-kubmaster-infra-03:
      access_ip: 10.130.0.26
      ansible_host: 10.130.0.26
      ip: 10.130.0.26
    otus-kubworker-infra-01:
      access_ip: 10.128.0.14
      ansible_host: 10.128.0.14
      ip: 10.128.0.14
    otus-kubworker-infra-02:
      access_ip: 10.129.0.5
      ansible_host: 10.129.0.5
      ip: 10.129.0.5
    otus-kubworker-app-01:
      access_ip: 10.130.0.27
      ansible_host: 10.130.0.27
      ip: 10.130.0.27
  children:
    kube-master:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    kube-node:
      hosts:
        otus-kubworker-infra-01:
        otus-kubworker-infra-02:
        otus-kubworker-app-01:
    etcd:
      hosts:
        otus-kubmaster-infra-01:
        otus-kubmaster-infra-02:
        otus-kubmaster-infra-03:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
