---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: monitoring
spec:
  # Add fields here
  retentionPeriod: "2"
  vmstorage:
    replicaCount: 1
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    storageDataPath: "/data/vm/cluster"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
  vmselect:
    replicaCount: 1
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
  vminsert:
    replicaCount: 1
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vmstorage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /data/vm/cluster
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - otus-kubworker-infra-01
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem