# Default values for sock-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
    registry: ''

rabbitmq:
    image:
        repo: rabbitmq
        tag: 3.6.8
    resources:
        requests:
            memory: 256Mi
            cpu: 350m
        limits:
            memory: 512Mi
            cpu: 1