---
apiVersion: operator.victoriametrics.com/v1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  probeSelector: {}
  probeNamespaceSelector: {}
  replicaCount: 1
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  serviceAccountName: vmagent
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    requests:
      cpu: "250m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  additionalArgs:
    memory.allowedPercent: "40"
  vmAgentExternalLabelName: vmagent
  externalLabels:
    cluster: {}
  remoteWrite:
    - url: "http://vminsert-vmcluster:8480/insert/0/prometheus/"