apiVersion: v1
kind: Secret
metadata:
  name: grafana-vm-datasources
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: VM
      type: prometheus
      url: http://vmselect-vmcluster.monitoring:8481/select/0/prometheus/
      access: proxy
      isDefault: true